name: "Publish website"
description: "Publish website to web hosting"
runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
        registry-url: 'https://registry.npmjs.org'
    - name: build website
      working-directory: ./webui
      run: |
        npm install
        npm run copy-docs
        npm run build-sitemap
        npm run build-website
      shell: bash
    - name: Install lftp
      run: sudo apt install lftp
      shell: bash
    - name: deploy website
      working-directory: ./webui/dist
      run: lftp -e 'set sftp:connect-program "ssh -a -x -oHostKeyAlgorithms=+ssh-rsa"; set ftp:ssl-force no; set ssl:verify-certificate no; set sftp:auto-confirm yes; mirror -R --delete ./ ./;' -u ${{ secrets.FTP_USERNAME }},${{ secrets.FTP_PASSWORD }} -p 5544 sftp://${{ secrets.FTP_SERVER }}
      shell: bash
