components:
  schemas:
    Schema:
      type: object
      properties:
        ref:
          type: string
        type:
          type: string
        properties:
          $ref: '#/components/schemas/Schema'
        enum:
          type: array
          items:
            type: object