components:
  schemas:
    Schema:
      ref:
        type: string
      type:
        type: string
      properties:
        type: array
        items:
          type: object
          properties:
            name:
              type: string
            value:
              $ref: '#/components/schemas/schema'
      enum:
        type: array
        items:
          type: object