openapi: 3.0.0
info:
  title: Sharepoint API used in PostWeb
  description: Sharepoint Feed Api
  version: 0.1
servers:
  - url: http://mokapi
    description: Container mokapi
paths:
  /postsearch/_vti_bin/sites.asmx:
    get:
      responses:
        '200':
          content:
            text/xml:
              schema:
                type: string
                x-mokapi-resource:
                  - name: wsdl.txt
  /postsearch/_vti_bin/client.svc/ProcessQuery:
    post:
      summary: Returns search results
      x-mokapi-middlewares:
        - type: replaceContent
          replacement:
            from: requestBody
            selector: //Method[@Name='ExecuteQuery']/@Id
          regex: ___QueryId___
      x-mokapi-resources:
        - name: search_po.txt
          if: body["//SetProperty[@Name='QueryText']/Parameter"] LIKE "p%"
      responses:
        '200':
          content:
            application/json:
              schema: 
                
  
        