version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    target-branch: develop
    schedule:
      interval: "weekly"
      day: friday
  - package-ecosystem: "npm"
    directory: "/webui"
    target-branch: develop
    schedule:
      interval: "weekly"
      day: "friday"
