project_name: mokapi
builds:
  - env:
      - CGO_ENABLED=0
    ldflags:
      - -X mokapi/version.BuildVersion={{ .Version }}
    main: ./cmd/mokapi
    goos:
      - linux
    goarch:
      - amd64
archives:
  - name_template: '{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}'
    format: tar.gz
checksum:
  name_template: "{{ .ProjectName }}_v{{ .Version }}_checksums.txt"
snapshot:
  name_template: "{{ .Version }}"
dockers:
  - goos: linux
    goarch: amd64
    image_templates:
      - "mokapi/mokapi:latest"
      - "mokapi/mokapi:{{ .Tag }}"
    dockerfile: Dockerfile-linux
    use: buildx