version: 2
project_name: mokapi
builds:
  - env:
      - CGO_ENABLED=0
    ldflags:
      - -X mokapi/version.BuildVersion={{ .Version }}
      - -X mokapi/version.BuildTime={{ .Date }}
    main: ./cmd/mokapi
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
archives:
  - name_template: '{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}'
    format: tar.gz
checksum:
  name_template: "{{ .ProjectName }}_v{{ .Version }}_linux_checksums.txt"

dockers:
  - goos: linux
    goarch: amd64
    image_templates:
      - "mokapi/mokapi:latest"
      - "mokapi/mokapi:{{ .Tag }}"
    dockerfile: images/release-alpine.Dockerfile
    use: buildx
  - goos: linux
    goarch: amd64
    image_templates:
      - "mokapi/mokapi:noble"
      - "mokapi/mokapi:{{ .Tag }}-noble"
    dockerfile: images/release-ubuntu.Dockerfile
    use: buildx
  - goos: darwin
    goarch: arm64
    image_templates:
      - "mokapi/mokapi:noble"
      - "mokapi/mokapi:{{ .Tag }}-noble"
    dockerfile: images/release-ubuntu.Dockerfile
    use: buildx

brews:
  - repository:
      owner: marle3003
      name: homebrew-tap
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
    homepage: https://mokapi.io
    description: "Easy and flexible API mocking using Go and Javascript - https://mokapi.io"

nfpms:
  - license: MIT
    maintainer: Marcel Lehmann
    homepage: https://mokapi.io
    description: "Easy and flexible API mocking using Go and Javascript - https://mokapi.io"
    formats:
      - rpm
      - deb