version: 2
project_name: mokapi
builds:
  - env:
      - CGO_ENABLED=0
    ldflags:
      - -s
      - -w
      - -X mokapi/version.BuildVersion={{ .Version }}
      - -X mokapi/version.BuildTime={{ .Date }}
    main: ./cmd/mokapi
    goos:
      - windows
    goarch:
      - amd64
archives:
  - name_template: '{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}'
    formats: [ 'zip' ]
checksum:
  name_template: "{{ .ProjectName }}_v{{ .Version }}_windows_checksums.txt"
snapshot:
  version_template: "{{ .Version }}"

chocolateys:
  - name: mokapi
    owners: Marcel Lehmann
    title: Mokapi
    authors: Marcel Lehmann
    project_url: https://mokapi.io
    package_source_url: https://github.com/marle3003/mokapi
    icon_url: https://cdn.jsdelivr.net/gh/marle3003/mokapi/webui/public/logo.svg
    copyright: 2021 Marcel Lehmann
    license_url: https://raw.githubusercontent.com/marle3003/mokapi/main/LICENSE
    require_license_acceptance: false
    project_source_url: https://github.com/marle3003/mokapi
    docs_url: https://mokapi.io/docs/guides
    bug_tracker_url: https://github.com/marle3003/mokapi/issues
    tags: "cross-platform testing devops api mock http kafka rest smtp ldap contract openapi asyncapi"
    summary: Your API Mocking Tool for Agile Development using Go and Javascript
    description: |
      **Mokapi** is an open-source tool that allows Agile, DevOps and Continuous Deployment teams
      to create and test API designs before actually building them.
      
      With Mokapi you can quickly and easily test various
      scenarios, such as delayed or failed responses without
      having to rely on a fully functional API.
      
      Mokapi helps you improve the quality of APIs and
      reduces the risk of bugs or errors in production.
      
      Its core feature are:
      
      - **Multiple Protocol support**: HTTP, HTTPS, Apache Kafka, SMTP, LDAP
      - **Everything as Code**: Reusing, version control, consistency and integrate mocks with your CI/CD.
      - **An embedded JavaScript engine** to control everything - status, headers, delays, errors or other edge cases.
      - **Patch Configuration** changes for mocking needs, rather than changing the original contract
      - **Multiple Provider support**: File, HTTP, GIT, NPM to gather configurations and scripts.
      - **Dashboard** to see what's going on.
      
      **Usage:***
      ```
      mokapi https://petstore31.swagger.io/api/v31/openapi.json
      ```
    release_notes: "https://github.com/marle3003/mokapi/releases/tag/v{{ .Version }}"

    url_template: "https://github.com/marle3003/mokapi/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    api_key: "{{ .Env.CHOCOLATEY_API_KEY }}"
    source_repo: "https://push.chocolatey.org/"
    skip_publish: false
