# This is an example .goreleaser.yml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
project_name: mokapi
builds:
  - id: mokapi
    env:
      - CGO_ENABLED=0
    ldflags:
      - -X mokapi/version.BuildVersion={{ .Version }}
    main: ./cmd/mokapi
    goos:
      - linux
      - windows
    goarch:
      - amd64
archives:
  - id: mokapi
    name_template: '{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}'
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: "{{ .ProjectName }}_v{{ .Version }}_checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
dockers:
  - goos: linux
    goarch: amd64
    ids:
      - mokapi
    image_templates:
      - "mokapi/mokapi:latest"
      - "mokapi/mokapi:{{ .Tag }}"
    dockerfile: Dockerfile-linux
    use: buildx
