# https://taskfile.dev

version: '3'

tasks:
  default:
    deps: [clean]
    cmds:
      - task: bindata-vueapp
      - task: build-windows
  build-windows:
    cmds:
      - go build -o mokapi_windows-amd64.exe -ldflags="-X 'mokapi/version.BuildVersion=1.0'" ./cmd/mokapi
    env:
      GOOS: windows
      GOARCH: amd64
  bindata-vueapp:
    deps: [build-vue-app]
    cmds:
      - go-bindata -nomemcopy -pkg api -o server/api/dashboard.go -prefix webui/dist/ webui/dist/...
  clean:
    dir: webui
    cmds:
      - npm run clean
  build-vue-app:
    dir: webui
    cmds:
      - npm run copy-docs
      - npm run build

