mail: '1.0'
info:
  title: Mokapi's Mail Server
servers:
  smtp:
    host: localhost:25
    protocol: smtp
  imap:
    host: localhost:143
    protocol: imap
rules:
  recipientDomainIsMokapi:
    description: Recipient's domain is mokapi.io
    recipient: '@mokapi.io'
    action: allow
mailboxes:
  bob@mokapi.io:
    username: bob
    password: bob123
    folders:
      Trash:
        flags: [\Trash]
  alice@mokapi.io:
    username: alice@mokapi.io

