mail: '1.0'
info:
  title: Mokapi's Mail Server
servers:
  smtp:
    host: localhost:8025
  imap:
    host: localhost:143
rules:
  - name: Recipient's domain is mokapi.io
    recipient: '@mokapi.io'
    action: allow
mailboxes:
  bob@mokapi.io:
    username: bob
    password: bob123
    folders:
      Trash:
        flags: [\Trash]
  alice@mokapi.io: {}

