mail: 1.0
info:
  title: Mokapi MailServer
servers:
  smtps:
    host: localhost:8025
    protocol: smtps
  customImaps:
    host: mail.mokapi.local:8993
    protocol: imaps
  dynamicImaps:
    host: imap.mokapi.local:8994
    protocol: imaps
rules:
  allowSender:
    sender: .*@foo.bar
    action: allow