name: "Build Mokapi image"
description: "Builds and deploys the React frontend to AWS S3"
inputs:
  image-name:
    required: true
    description: "The image name to build"
  artifact-name:
    required: true
    description: "The upload artifact name"
  version:
    required: true
    description: "The version of mokapi to build"
    type: string
runs:
  using: "composite"
  steps:
    - name: Build docker alpha image
      run: docker build --build-arg VERSION=${{ inputs.version }} -t ${{ inputs.image-name }} -t mokapi/mokapi:alpha -f ./images/alpha.Dockerfile .
      shell: bash
    - name: Save Image to file
      run: docker save -o /tmp/mokapi.tar ${{ inputs.image-name }} mokapi/mokapi:alpha
      shell: bash
    - name: Upload image
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.artifact-name }}
        path: /tmp/mokapi.tar