name: "Build Mokapi image"
inputs:
  image-name:
    required: true
    description: "The image name to build"
  artifact-name:
    required: true
    description: "The upload artifact name"
  version:
    required: true
    description: "The version of mokapi to build"
  latest-tag:
    required: true
    description: "The latest tag"
runs:
  using: "composite"
  steps:
    - uses: actions/setup-go@v5
      with:
        go-version: 1.25.5
    - uses: ./.github/actions/build-cli-flags-doc
    - uses: ./.github/actions/build-alpha-release-notes
      with:
        version: ${{ inputs.version }}
        latest-tag: ${{ inputs.latest-tag }}
    - name: Build docker alpha image
      run: docker build --build-arg VERSION=${{ inputs.version }} -t ${{ inputs.image-name }} -t mokapi/mokapi:alpha -f ./images/alpha.Dockerfile .
      shell: bash
    - name: Save Image to file
      run: docker save -o /tmp/mokapi.tar ${{ inputs.image-name }} mokapi/mokapi:alpha
      shell: bash
    - name: Upload image
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.artifact-name }}
        path: /tmp/mokapi.tar