openapi: 3.0.0
info:
  title: Sample API
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 0.1.9
  x-server-configuration:
    data:
      file:
        filename: "data.yml"

servers:
  - url: http://demo
    description: Optional server description, e.g. Main (production) server
  - url: http://staging-api.example.com:7001
    description: Optional server description, e.g. Internal staging server for testing
paths:
  /users/{userId}:
    get:
      summary: Returns a list of users.
      description: Optional extended description in CommonMark or HTML.
      parameters:
          - in: path
            name: userId
            required: true
            schema:
                type: integer
            description: Nummeric ID of the user to get
      responses:
        '200':    # status code
          description: Success A JSON array of user names
          content:
            application/json:
              schema: 
                x-resource: users
                type: array
                items:
                  $ref: '#/components/schemas/User'
components:
  schemas:
    Address:
      type: object
      properties:
        id:
          type: integer
          x-faker: numbers.uint32
        street:
          type: string
    User:
      type: object
      properties:
        id:
          type: integer
          x-faker: numbers.uint32
        name:
          type: string
          x-faker: person.last
        address:
          $ref: '#/components/schemas/Address'