openapi: 3.0.0
info:
  title: Sample API
components:
  schemas:
    Address:
      type: object
      properties:
        id:
          type: integer
          x-faker: numbers.uint32
        street:
          type: string
    User:
      type: object
      properties:
        id:
          type: integer
          x-faker: numbers.uint32
        name:
          type: string
          x-faker: person.last
        address:
          $ref: '#/components/schemas/Address'