ldap: 1.0.0
server: 
    listen: "0.0.0.0:389"
    rootDomainNamingContext: dc=postweb,dc=ch
    subSchemaSubentry: cn=schema,dc=postweb,dc=ch
    namingContexts:
        - dc=postweb,dc=ch
        - cn=schema,dc=postweb,dc=ch
entries:
    - dn: dc=postweb,dc=ch
      objectClass: top
    - dn: cn=users,dc=postweb,dc=ch
      objectClass: top
    - dn: cn=lehmannmar,cn=users,dc=postweb,dc=ch
      objectClass: user
      memberOf: CN=Z-SC-PostWeb-P-Group,dc=postweb,dc=ch
      thumbnailphoto: 
        file: ./cn=lehmannmar_thumbnailPhoto.png
    - dn: cn=schema,dc=postweb,dc=ch
      objectClass:
        - subSchema
        - subEntry
        - top
      objectClasses:
        - ( 2.5.6.0 NAME ( 'top' ) ABSTRACT MUST ( objectClass ) )
        - ( 1.2.840.113556.1.5.9 NAME ( 'user' ) SUP ( top ) MUST ( cn ) MAY ( memberOf, thumbnailphoto ) )
      attributeTypes:
        - ( 2.5.21.6 NAME ( 'objectClass' ) DESC 'LDAP object classes' SYNTAX 1.3.6.1.4.1.1466.115.121.1.37 USAGE directoryOperation )
        - ( 2.5.21.5 NAME ( 'attributeTypes' ) DESC 'LDAP attribute types' SYNTAX 1.3.6.1.4.1.1466.115.121.1.3 USAGE directoryOperation )
        - ( 2.5.4.3 NAME ( 'cn' ) SYNTAX 1.3.6.1.4.1.1466.115.121.1.15 USAGE userApplications )
        - ( 1.2.840.113556.1.2.102 NAME ( 'memberOf' ) SYNTAX 1.3.6.1.4.1.1466.115.121.1.12 USAGE userApplications )
        - ( 2.16.840.1.113730.3.1.35 NAME ( 'thumbnailphoto' ) SYNTAX 1.3.6.1.4.1.1466.115.121.1.40 USAGE userApplications SINGLE-VALUE ) 