openapi: 3.0.0
info:
  title: PressReview API used in PostWeb
  description: 
  version: 0.1
  x-server-configuration:
    data:
     file:
       filename: data.yml
servers:
  - url: http://mokapi/pressreview/Feed
    description: Container mokapi
paths:
  /Get:
    get:
      summary: Returns press review feed
      responses:
        '200':    # status code
          content:
            application/rss+xml:
              schema: 
                x-resource: rss
                type: object
                xml:
                  name: rss
                properties:
                  version:
                    type: string
                    xml:
                      attribute: true
                  atom:
                    type: string
                    xml:
                      attribute: true
                      prefix: xmlns
                  dc:
                    type: string
                    xml:
                      attribute: true
                      prefix: xmlns
                  channel:
                    $ref: '#/components/schemas/Channel'
                        

components:
  schemas:
    Item:
      type: object
      properties:
        title:
          type: string
          xml:
            cdata: true
        link:
          type: string
        lead:
          type: string
          xml:
            name: CustomField_Lead
        pubDate:
          type: string
        publisher:
          type: string
          xml:
            prefix: dc
        category:
          type: string
        language:
          type: string
          xml:
            prefix: dc
            name: ISO639-2
        lieferdatum:
            type: string
            xml:
              name: CustomField_Lieferdatum
    Channel:
      type: object
      properties:
        title: 
          type: string
        link: 
          type: string
        description:
          type: string
        language:
          type: string
        lastBuildDate:
          type: string
        item:
          type: array
          items: 
            $ref: '#/components/schemas/Item'
        