nav:
  - "Welcome": "welcome.md"
  - "Config": "config.md"
  - "OpenAPI":
    - "Intro": "openapi/intro.md"
    - "Response": "openapi/response.md"
    - "HTTPS & TLS": "openapi/tls.md"
  - "Kafka": "kafka.md"
  - "LDAP": "ldap.md"
  - "Actions":
    - "Intro": "actions/intro.md"
    - "Syntax": "actions/syntax.md"
    - "Context and expression": "actions/context.md"
    - "Operators": "actions/operators.md"
    - "Functions": "actions/functions.md"
    - "Actions": "actions/actions.md"
    - "Events": "actions/events.md"