nav:
  - "Welcome": "welcome.md"
  - "Config": "config.md"
  - "OpenAPI":
    - "Intro": "openapi/intro.md"
    - "Response": "openapi/response.md"
    - "HTTPS & TLS": "openapi/tls.md"
  - "Kafka": "kafka.md"
  - "LDAP": "ldap.md"
  - "SMTP": "smtp.md"
  - "Javascript": "javascript.md"
  - "Lua": "lua.md"