name: "Build Mokapi CLI Flags doc"
runs:
  using: composite
  steps:
    - name: Create directory and file
      shell: bash
      run: |
        mkdir -p webui/dist
        touch webui/dist/.tmp
    - name: Build CLI doc
      shell: bash
      run: go run ./cmd/internal/gen-cli-docs/main.go
    - name: Add CLI Flags nav entry
      working-directory: ./docs
      shell: bash
      run: |
        jq '.Configuration.items.Static.items["CLI Flags"] = "configuration/static/mokapi.md"' ./config.json > ./tmp.json
        mv ./tmp.json ./config.json