name: "Build Mokapi CLI Flags doc"
runs:
  using: composite
  steps:
    - name: Create dist directory and file
      shell: bash
      run: |
        mkdir -p webui/dist
        touch webui/dist/.tmp
    - name: Build CLI doc
      shell: bash
      run: go run ./cmd/internal/gen-cli-docs/main.go