name: "Get next patch version"
runs:
  using: "composite"
  steps:
    - name: get version
      id: get_version
      run: |
        # Fetch tags from main
        git fetch --tags --force origin main

        # Get the latest tag from main
        LATEST_TAG=$(git describe --tags --abbrev=0 --match "v*" origin/main || echo "0.0.0")
        echo "Latest tag from main: $LATEST_TAG"

        # Split version into major, minor, patch
        IFS='.' read -r MAJOR MINOR PATCH <<< "${LATEST_TAG//[!0-9.]/}"

        # Increment patch version
        PATCH=$((PATCH + 1))
        NEW_VERSION="$MAJOR.$MINOR.$PATCH"

        echo "New version: $NEW_VERSION"
        echo "version=$NEW_VERSION" >> $GITHUB_OUTPUT