name: "Publish docker image"
description: "Publish docker image to docker repository"
inputs:
  image-name:
    required: true
    description: "The mokapi image name"
  artifact-name:
    required: true
    description: "The artifact name to download image"
runs:
  using: "composite"
  steps:
    - name: Download image
      id: download
      uses: actions/download-artifact@v3
      with:
        name: ${{ inputs.artifact-name }}
        path: /tmp
    - name: Load image
      run: docker load --input ${{steps.download.outputs.download-path}}
      shell: bash
    - name: Login to Docker
      uses: docker/login-action@v1
      with:
        username: mokapi
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Push image to Docker
      run: docker push ${{ inputs.image-name }}
      shell: bash