# This is an example .goreleaser.yml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
project_name: mokapi
builds:
  - id: mokapi
    env:
      - CGO_ENABLED=0
    ldflags:
      - -X mokapi/version.BuildVersion={{ .Branch }}
    main: ./cmd/mokapi
    goos:
      - linux
      - windows
    goarch:
      - amd64
dockers:
  - goos: linux
    goarch: amd64
    ids:
      - mokapi
    image_templates:
      - "mokapi/mokapi:{{ .Branch }}-beta"
    dockerfile: Dockerfile-linux
    use: buildx
