name: Release alpha
on:
  push:
    branches:
      - v*

env:
  image-name: mokapi/mokapi:${GITHUB_REF##*/}-alpha
  image-artifact-name: mokapi-image
  artifact-test-report: playwright-report
  report-publish-path: reports/${{ github.ref_name }}

jobs:
  build-alpha:
    uses: ./.github/workflows/test.yml
    with:
      image-name: mokapi/mokapi:${GITHUB_REF##*/}-alpha
      image-artifact-name: mokapi-image
      artifact-test-report: playwright-report
      report-publish-path: reports/${{ github.ref_name }}
      version: ${GITHUB_REF##*/v}

  publish-image:
    name: Publish docker image
    runs-on: ubuntu-latest
    if: "success()"
    needs: [ build-alpha ]
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/actions/publish-docker-image
        with:
          image-name: ${{ env.image-name }}
          artifact-name: ${{ env.image-artifact-name }}
          docker-username: mokapi
          docker-password: ${{ secrets.DOCKER_PASSWORD }}

  publish-website:
    name: Publish website
    runs-on: ubuntu-latest
    if: "success()"
    needs: [ build-alpha ]
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Restore Timestamps
        uses: chetan/git-restore-mtime-action@v2
      - uses: ./.github/actions/publish-website
        with:
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server: ${{ secrets.FTP_SERVER }}

