name: Release alpha
on:
  push:
    branches:
      - v*

env:
  image-name: mokapi/mokapi:${GITHUB_REF##*/}-alpha
  image-artefact-name: mokapi-image
  artifact-test-report: playwright-report
  report-publish-path: reports/${{ github.ref_name }}

jobs:
  build:
    name: Build alpha
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/build-mokapi-image@v1
        with:
          image-name: ${{ env.image-name }}
          artifact-name: ${{ env.image-artefact-name }}

  test:
    name: Run UI tests
    runs-on: ubuntu-latest
    if: "success()"
    needs: [ build ]
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/run-frontend-tests@v1
        with:
          image-name: ${{ env.image-name }}
          artefact-name: ${{ env.image-artefact-name }}

  publish-report:
    name: Publish Playwright Report
    if: "success() || needs.test.result == 'failure'"
    needs: [ test ]
    runs-on: ubuntu-latest
    continue-on-error: true
    env:
      HTML_REPORT_URL_PATH: reports/${{ github.ref_name }}
    steps:
      - name: Checkout GitHub Pages Branch
        uses: actions/checkout@v2
        with:
          ref: gh-pages
      - uses: actions/publish-test-report@v1
        with:
          artefact-name: ${{ env.image-artefact-name }}
          test-report-path: ${{ env.report-publish-path }}

  publish-image:
    name: Publish docker image
    runs-on: ubuntu-latest
    if: "success()"
    needs: [ test ]
    steps:
      - uses: actions/publish-docker-image@v1
        with:
          image-name: ${{ env.image-name }}
          artefact-name: ${{ env.image-artefact-name }}

  publish-website:
    name: Publish website
    runs-on: ubuntu-latest
    if: "success()"
    needs: [ test ]
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/publish-website@v1

