name: Release alpha
on:
  push:
    branches:
      - v*

env:
  image-name: mokapi/mokapi:${GITHUB_REF##*/}-alpha
  image-artifact-name: mokapi-image
  artifact-test-report: playwright-report
  report-publish-path: reports/${{ github.ref_name }}

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - uses: ./.github/workflows/test.yml
        with:
          image-name: ${{ env.image-name }}
          image-artifact-name: ${{ env.image-artifact-name }}
          artifact-test-report: ${{ env.artifact-test-report }}
          report-publish-path: ${{ env.report-publish-path }}

  publish-image:
    name: Publish docker image
    runs-on: ubuntu-latest
    if: "success()"
    needs: [ test ]
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: ./.github/actions/publish-docker-image
        with:
          image-name: ${{ env.image-name }}
          artifact-name: ${{ env.image-artifact-name }}
          docker-username: mokapi
          docker-password: ${{ secrets.DOCKER_PASSWORD }}

  publish-website:
    name: Publish website
    runs-on: ubuntu-latest
    if: "success()"
    needs: [ test ]
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - uses: ./.github/actions/publish-website
        with:
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server: ${{ secrets.FTP_SERVER }}

