name: Release alpha
on:
  push:
    branches:
      - v*

jobs:
  release:
    name: Release alpha
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Login to Docker
        uses: docker/login-action@v1
        with:
          username: mokapi
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build docker alpha image
        run: docker build --build-arg VERSION=${GITHUB_REF##*/v} -t mokapi/mokapi:${GITHUB_REF##*/}-alpha -f ./images/alpha.Dockerfile .
      - name: Test
        run: docker run --rm mokapi/mokapi:${GITHUB_REF##*/}-alpha
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies
        working-directory: ./webui
        run: npm ci
      - name: Install Playwright
        working-directory: ./webui
        run: npx playwright install --with-deps
      - name: Run your tests
        working-directory: ./webui
        run: npx playwright test
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        working-directory: ./webui
        with:
          name: playwright-report
          path: playwright-reports
