name: Release alpha
on:
  push:
    branches:
      - develop

env:
  image-name: mokapi/mokapi:${GITHUB_REF##*/v}-alpha
  image-artifact-name: mokapi-image
  artifact-test-report: playwright-report
  report-publish-path: reports/${{ github.ref_name }}

jobs:
  init:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_version.outputs.version }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensure all tags are fetched
      - uses: ./.github/actions/get-next-patch-version
        id: get_version
  build-alpha:
    needs: init
    uses: ./.github/workflows/test.yml
    with:
      image-name: mokapi/mokapi:${GITHUB_REF##*/v}-alpha
      image-artifact-name: mokapi-image
      artifact-test-report: playwright-report
      report-publish-path: reports/${{ github.ref_name }}
      version: ${{ needs.init.outputs.version }}

  publish-image:
    name: Publish docker image
    runs-on: ubuntu-latest
    if: "success()"
    needs: build-alpha
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/actions/publish-docker-image
        with:
          image-name: ${{ env.image-name }}
          artifact-name: ${{ env.image-artifact-name }}
          docker-username: marle3003
          docker-password: ${{ secrets.DOCKER_PASSWORD }}

  publish-website:
    name: Publish website
    runs-on: ubuntu-latest
    if: "success()"
    needs: [ build-alpha ]
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Restore Timestamps
        uses: chetan/git-restore-mtime-action@v2
      - uses: ./.github/actions/publish-website
        with:
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server: ${{ secrets.FTP_SERVER }}
          token: ${{ secrets.GITHUB_TOKEN }}

