name: Release alpha
on:
  push:
    branches:
      - v*

jobs:
  init:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_version.outputs.version }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensure all tags are fetched
      - uses: ./.github/actions/get-next-patch-version
        id: get_version
  build-alpha:
    runs-on: ubuntu-latest
    needs: init
    steps:
      - name: Use Latest Tag from Setup
        run: |
          echo "Latest tag is ${{ needs.init.outputs.version }}"