name: Test Pull-Request
on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  pull-request:
    uses: ./.github/workflows/test.yml
    with:
      image-name: mokapi/mokapi:${GITHUB_REF##*/}-alpha
      image-artifact-name: mokapi-image
      artifact-test-report: playwright-report
      report-publish-path: reports/${{ github.ref_name }}