name: Release
on:
  release:
    types: [published]

permissions:
  id-token: write # Required for OIDC
  contents: write

jobs:

  release-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.25.5
      - uses: ./.github/actions/build-release-notes
      - uses: actions/setup-node@v4
        with:
          node-version: 24
          registry-url: 'https://registry.npmjs.org'
      - run: npm install
        working-directory: ./webui
      - name: Install taskfile
        run: sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b ~/.local/bin
      - name: Publish
        run: task publish-npm-package VERSION=${GITHUB_REF##*/v}
        env:
          CGO_ENABLED: 0